# Generated by Django 5.0.4 on 2024-04-17 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_regex', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='whitelist',
            field=models.BooleanField(default=True),
        ),
    ]
