# Generated by Django 5.0.4 on 2024-04-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_websiteblock_rename_due_date_task_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteblock',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
